spring.application.name=notification-service

server.port = 9060

spring.datasource.url=jdbc:postgresql://localhost:5432/kafka
spring.datasource.username=root
spring.datasource.password=abhi2003#
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
